/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\vue\\Knowledge\\vuepress-starter\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-743043a0",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-743043a0").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-83beb1d6",
    path: "/view/Axios/type_2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-83beb1d6").then(next)
    },
  },
  {
    name: "v-07ec9527",
    path: "/view/Axios/vue_proxy%E8%A7%A3%E5%86%B3%E8%B7%A8%E5%9F%9F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07ec9527").then(next)
    },
  },
  {
    path: "/view/Axios/vue_proxy解决跨域.html",
    redirect: "/view/Axios/vue_proxy%E8%A7%A3%E5%86%B3%E8%B7%A8%E5%9F%9F.html"
  },
  {
    path: "/view/Axios/vue_proxy解决跨域.html",
    redirect: "/view/Axios/vue_proxy%E8%A7%A3%E5%86%B3%E8%B7%A8%E5%9F%9F.html"
  },
  {
    name: "v-165fae61",
    path: "/view/Css/one.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-165fae61").then(next)
    },
  },
  {
    name: "v-5824dbd6",
    path: "/view/Css/two.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5824dbd6").then(next)
    },
  },
  {
    name: "v-f9ca8496",
    path: "/view/Axios/type_1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f9ca8496").then(next)
    },
  },
  {
    name: "v-67b3397b",
    path: "/view/Js/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67b3397b").then(next)
    },
  },
  {
    name: "v-371273db",
    path: "/view/Js/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-371273db").then(next)
    },
  },
  {
    name: "v-1b34277b",
    path: "/view/RegExp/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b34277b").then(next)
    },
  },
  {
    name: "v-671a995b",
    path: "/view/RegExp/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-671a995b").then(next)
    },
  },
  {
    name: "v-513316d5",
    path: "/view/Vue/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-513316d5").then(next)
    },
  },
  {
    name: "v-5f80e4f5",
    path: "/view/Vue/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f80e4f5").then(next)
    },
  },
  {
    name: "v-6dceb315",
    path: "/view/Vue/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6dceb315").then(next)
    },
  },
  {
    name: "v-14cbffb6",
    path: "/view/map/coordinate-conversion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14cbffb6").then(next)
    },
  },
  {
    name: "v-9326ecf2",
    path: "/view/echarts/map.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9326ecf2").then(next)
    },
  },
  {
    name: "v-67663055",
    path: "/view/map/gaode1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67663055").then(next)
    },
  },
  {
    name: "v-25695416",
    path: "/view/map/gaode2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25695416").then(next)
    },
  },
  {
    name: "v-73307b95",
    path: "/view/map/gaode3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73307b95").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]