/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "星星的泪痕",
  "description": "知识记录",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/logo.jpg"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "01.jpg",
        "heroImageStyle": {
          "maxWidth": "600px",
          "width": "100%",
          "display": "block",
          "margin": "9rem auto 2rem",
          "background": "#fff",
          "borderRadius": "1rem"
        },
        "footer": null
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-743043a0",
      "path": "/"
    },
    {
      "title": "axios 简单封装type2",
      "frontmatter": {
        "title": "axios 简单封装type2",
        "date": "2022-03-01T00:00:00.000Z",
        "tags": [
          "axios"
        ],
        "categories": [
          "frontEnd"
        ]
      },
      "regularPath": "/view/Axios/type_2.html",
      "relativePath": "view/Axios/type_2.md",
      "key": "v-83beb1d6",
      "path": "/view/Axios/type_2.html"
    },
    {
      "title": "通过vue的proxy解决前端请求跨域问题",
      "frontmatter": {},
      "regularPath": "/view/Axios/vue_proxy%E8%A7%A3%E5%86%B3%E8%B7%A8%E5%9F%9F.html",
      "relativePath": "view/Axios/vue_proxy解决跨域.md",
      "key": "v-07ec9527",
      "path": "/view/Axios/vue_proxy%E8%A7%A3%E5%86%B3%E8%B7%A8%E5%9F%9F.html",
      "headers": [
        {
          "level": 2,
          "title": "通过vue的proxy解决前端请求跨域问题",
          "slug": "通过vue的proxy解决前端请求跨域问题"
        }
      ]
    },
    {
      "title": "通过border实现三角",
      "frontmatter": {
        "title": "通过border实现三角",
        "date": "2022-02-28T00:00:00.000Z",
        "tags": [
          "Css"
        ],
        "categories": [
          "frontEnd"
        ]
      },
      "regularPath": "/view/Css/one.html",
      "relativePath": "view/Css/one.md",
      "key": "v-165fae61",
      "path": "/view/Css/one.html",
      "headers": [
        {
          "level": 2,
          "title": "通过border实现三角",
          "slug": "通过border实现三角"
        }
      ]
    },
    {
      "title": "切换分辨率，banner图水平居中",
      "frontmatter": {
        "title": "切换分辨率，banner图水平居中",
        "date": "2022-03-01T00:00:00.000Z",
        "tags": [
          "Css"
        ],
        "categories": [
          "frontEnd"
        ]
      },
      "regularPath": "/view/Css/two.html",
      "relativePath": "view/Css/two.md",
      "key": "v-5824dbd6",
      "path": "/view/Css/two.html"
    },
    {
      "title": "axios 简单封装type1",
      "frontmatter": {
        "title": "axios 简单封装type1",
        "date": "2022-03-01T00:00:00.000Z",
        "tags": [
          "axios"
        ],
        "categories": [
          "frontEnd"
        ]
      },
      "regularPath": "/view/Axios/type_1.html",
      "relativePath": "view/Axios/type_1.md",
      "key": "v-f9ca8496",
      "path": "/view/Axios/type_1.html"
    },
    {
      "title": "移动端调试工具",
      "frontmatter": {},
      "regularPath": "/view/Js/1.html",
      "relativePath": "view/Js/1.md",
      "key": "v-67b3397b",
      "path": "/view/Js/1.html",
      "headers": [
        {
          "level": 2,
          "title": "移动端调试工具",
          "slug": "移动端调试工具"
        },
        {
          "level": 3,
          "title": "1.  VConsole 类似于微信小程序的移动端调试效果",
          "slug": "_1-vconsole-类似于微信小程序的移动端调试效果"
        },
        {
          "level": 3,
          "title": "2.  charles 通过代理手机wifi，可以查看手机所发出的请求",
          "slug": "_2-charles-通过代理手机wifi-可以查看手机所发出的请求"
        }
      ]
    },
    {
      "title": "日期、时间格式化",
      "frontmatter": {
        "title": "日期、时间格式化",
        "date": "2022-03-01T00:00:00.000Z",
        "tags": [
          "Js",
          "Tool"
        ],
        "categories": [
          "frontEnd"
        ]
      },
      "regularPath": "/view/Js/2.html",
      "relativePath": "view/Js/2.md",
      "key": "v-371273db",
      "path": "/view/Js/2.html",
      "headers": [
        {
          "level": 2,
          "title": "日期、时间格式化",
          "slug": "日期、时间格式化"
        }
      ]
    },
    {
      "title": "设备判断",
      "frontmatter": {},
      "regularPath": "/view/RegExp/1.html",
      "relativePath": "view/RegExp/1.md",
      "key": "v-1b34277b",
      "path": "/view/RegExp/1.html",
      "headers": [
        {
          "level": 2,
          "title": "设备判断",
          "slug": "设备判断"
        }
      ]
    },
    {
      "title": "特殊校验",
      "frontmatter": {},
      "regularPath": "/view/RegExp/2.html",
      "relativePath": "view/RegExp/2.md",
      "key": "v-671a995b",
      "path": "/view/RegExp/2.html",
      "headers": [
        {
          "level": 2,
          "title": "特殊校验",
          "slug": "特殊校验"
        }
      ]
    },
    {
      "title": "windows环境搭建Vue开发环境",
      "frontmatter": {},
      "regularPath": "/view/Vue/01.html",
      "relativePath": "view/Vue/01.md",
      "key": "v-513316d5",
      "path": "/view/Vue/01.html",
      "headers": [
        {
          "level": 2,
          "title": "windows环境搭建Vue开发环境",
          "slug": "windows环境搭建vue开发环境"
        },
        {
          "level": 3,
          "title": "一、安装node.js",
          "slug": "一、安装node-js"
        },
        {
          "level": 3,
          "title": "二、设置nodejs prefix（全局）和cache（缓存）路径",
          "slug": "二、设置nodejs-prefix-全局-和cache-缓存-路径"
        },
        {
          "level": 3,
          "title": "三、基于 Node.js 安装cnpm（淘宝镜像）",
          "slug": "三、基于-node-js-安装cnpm-淘宝镜像"
        },
        {
          "level": 3,
          "title": "四、设置环境变量（非常重要）",
          "slug": "四、设置环境变量-非常重要"
        },
        {
          "level": 3,
          "title": "五、安装Vue",
          "slug": "五、安装vue"
        },
        {
          "level": 3,
          "title": "六、安装vue命令行工具，即vue-cli 脚手架",
          "slug": "六、安装vue命令行工具-即vue-cli-脚手架"
        }
      ]
    },
    {
      "title": "自定义指令进行权限管理",
      "frontmatter": {
        "title": "自定义指令进行权限管理",
        "date": "2022-03-01T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "frontEnd"
        ]
      },
      "regularPath": "/view/Vue/02.html",
      "relativePath": "view/Vue/02.md",
      "key": "v-5f80e4f5",
      "path": "/view/Vue/02.html",
      "headers": [
        {
          "level": 2,
          "title": "自定义指令进行权限管理",
          "slug": "自定义指令进行权限管理"
        }
      ]
    },
    {
      "title": "promise结合map的使用",
      "frontmatter": {},
      "regularPath": "/view/Vue/03.html",
      "relativePath": "view/Vue/03.md",
      "key": "v-6dceb315",
      "path": "/view/Vue/03.html",
      "headers": [
        {
          "level": 2,
          "title": "promise结合map的使用",
          "slug": "promise结合map的使用"
        }
      ]
    },
    {
      "title": "坐标系转换",
      "frontmatter": {},
      "regularPath": "/view/map/coordinate-conversion.html",
      "relativePath": "view/map/coordinate-conversion.md",
      "key": "v-14cbffb6",
      "path": "/view/map/coordinate-conversion.html",
      "headers": [
        {
          "level": 2,
          "title": "坐标系转换",
          "slug": "坐标系转换"
        }
      ]
    },
    {
      "title": "geojson地图下钻",
      "frontmatter": {},
      "regularPath": "/view/echarts/map.html",
      "relativePath": "view/echarts/map.md",
      "key": "v-9326ecf2",
      "path": "/view/echarts/map.html",
      "headers": [
        {
          "level": 2,
          "title": "geojson地图下钻",
          "slug": "geojson地图下钻"
        },
        {
          "level": 3,
          "title": "获取地图json数据",
          "slug": "获取地图json数据"
        },
        {
          "level": 3,
          "title": "下钻和返回",
          "slug": "下钻和返回"
        },
        {
          "level": 3,
          "title": "利用echarts使用json显示地图",
          "slug": "利用echarts使用json显示地图"
        }
      ]
    },
    {
      "title": "高德地图 绘制区域遮罩及边界线",
      "frontmatter": {},
      "regularPath": "/view/map/gaode1.html",
      "relativePath": "view/map/gaode1.md",
      "key": "v-67663055",
      "path": "/view/map/gaode1.html",
      "headers": [
        {
          "level": 2,
          "title": "高德地图 绘制区域遮罩及边界线",
          "slug": "高德地图-绘制区域遮罩及边界线"
        },
        {
          "level": 3,
          "title": "1.通过 AMap.DistrictSearch 搜索获取区域边界点，利用边界点信息通过AMap.Polygon绘制多边形",
          "slug": "_1-通过-amap-districtsearch-搜索获取区域边界点-利用边界点信息通过amap-polygon绘制多边形"
        },
        {
          "level": 3,
          "title": "2.通过DataV.GeoAtlas获取区域的geoJson数据,利用AMap.GeoJSON的getPolygon()方法",
          "slug": "_2-通过datav-geoatlas获取区域的geojson数据-利用amap-geojson的getpolygon-方法"
        }
      ]
    },
    {
      "title": "高德地图结合Vue自定义信息弹窗",
      "frontmatter": {},
      "regularPath": "/view/map/gaode2.html",
      "relativePath": "view/map/gaode2.md",
      "key": "v-25695416",
      "path": "/view/map/gaode2.html",
      "headers": [
        {
          "level": 2,
          "title": "高德地图结合Vue自定义信息弹窗",
          "slug": "高德地图结合vue自定义信息弹窗"
        }
      ]
    },
    {
      "title": "度°分′秒″转度",
      "frontmatter": {},
      "regularPath": "/view/map/gaode3.html",
      "relativePath": "view/map/gaode3.md",
      "key": "v-73307b95",
      "path": "/view/map/gaode3.html",
      "headers": [
        {
          "level": 2,
          "title": "度°分′秒″转度",
          "slug": "度°分′秒′′转度"
        }
      ]
    }
  ],
  "themeConfig": {
    "type": "blog",
    "authorAvatar": "/avatar.jpg",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      },
      "socialLinks": []
    },
    "noFoundPageByTencent": false,
    "mode": "light",
    "modePicker": false,
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "CSDN",
        "link": "https://blog.csdn.net",
        "target": "_blank"
      },
      {
        "text": "语言",
        "ariaLabel": "Language Menu",
        "items": [
          {
            "text": "中文",
            "link": "/language/chinese/"
          },
          {
            "text": "英文",
            "link": "/language/english/"
          }
        ]
      }
    ],
    "search": true,
    "searchMaxSuggestions": 10,
    "subSidebar": "auto",
    "sidebar": [
      {
        "title": "Axios",
        "collapsable": true,
        "sidebarDepth": 2,
        "children": [
          "/view/Axios/type_1",
          "/view/Axios/type_2",
          "/view/Axios/vue_proxy解决跨域"
        ]
      },
      {
        "title": "Css",
        "collapsable": true,
        "sidebarDepth": 2,
        "children": [
          "/view/Css/one",
          "/view/Css/two"
        ]
      },
      {
        "title": "echarts",
        "collapsable": true,
        "sidebarDepth": 2,
        "children": [
          "/view/echarts/map"
        ]
      },
      {
        "title": "Js",
        "collapsable": true,
        "sidebarDepth": 2,
        "children": [
          "/view/Js/1",
          "/view/Js/2"
        ]
      },
      {
        "title": "map",
        "collapsable": true,
        "sidebarDepth": 2,
        "children": [
          "/view/map/coordinate-conversion",
          "/view/map/gaode1",
          "/view/map/gaode2",
          "/view/map/gaode3"
        ]
      },
      {
        "title": "RegExp",
        "collapsable": true,
        "sidebarDepth": 2,
        "children": [
          "/view/RegExp/1",
          "/view/RegExp/2"
        ]
      },
      {
        "title": "Vue",
        "collapsable": true,
        "sidebarDepth": 2,
        "children": [
          "/view/Vue/01",
          "/view/Vue/02",
          "/view/Vue/03"
        ]
      }
    ]
  }
}