/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Css": {
      "key": "Css",
      "scope": "tags",
      "path": "/tag/Css/",
      "pageKeys": [
        "v-165fae61",
        "v-5824dbd6"
      ]
    },
    "axios": {
      "key": "axios",
      "scope": "tags",
      "path": "/tag/axios/",
      "pageKeys": [
        "v-f9ca8496",
        "v-83beb1d6"
      ]
    },
    "Js": {
      "key": "Js",
      "scope": "tags",
      "path": "/tag/Js/",
      "pageKeys": [
        "v-371273db"
      ]
    },
    "Tool": {
      "key": "Tool",
      "scope": "tags",
      "path": "/tag/Tool/",
      "pageKeys": [
        "v-371273db"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "tags",
      "path": "/tag/Vue/",
      "pageKeys": [
        "v-5f80e4f5"
      ]
    }
  },
  "categories": {
    "frontEnd": {
      "key": "frontEnd",
      "scope": "categories",
      "path": "/categories/frontEnd/",
      "pageKeys": [
        "v-165fae61",
        "v-f9ca8496",
        "v-83beb1d6",
        "v-371273db",
        "v-5824dbd6",
        "v-5f80e4f5"
      ]
    }
  },
  "timeline": {}
}