/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "Css",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/Css/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "axios",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/axios/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "Js",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/Js/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "Tool",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/Tool/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "Vue",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/Vue/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "frontEnd",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/frontEnd/","interval":[0,6]}],
  prevText: "Prev",
  nextText: "Next",
}]